wandb_version: 1

_wandb:
  desc: null
  value:
    code_path: code/reward.py
    python_version: 3.10.12
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1717427316.0576
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 1
      - 23
      4: 3.10.12
      5: 0.15.12
      8:
      - 5
      13: darwin-x86_64
